### ISSUE TITLE
Requests for tweaked display

### ISSUE THREAD

**Issue by brocktopus** [lingeringcode/rhetmap-time-series#1]
This is awesome! I have two requests--if I can make the adjustments myself, I'll put in pull requests of them. But in case you can hit them first:

1. The legend for the blue line (2012-2013, I assume?) is not visible when I view the site.
2. Can the week-related data placement be swapped from right-of-vertical-line to left-of-vertical-line when moving to the right half of the screen? As it stands, late-stage data gets displayed outside the window and is thus cut off.

Thanks for making this!

**Comment by lingeringcode** [comment]
Good catches! 

Re: #1: My job-market brain didn't even spot the blue line legend issue. LMK if you look into it. I won't have time for a few weeks to get back to this.

Re: #2: Good to know. And, again, same note about my ability to get back to this.

**Comment by lingeringcode** [comment]
Ok, easy fix for the 2012-13 label for the legend. No worries there. The other one I'll deal with later.

**Comment by lingeringcode** [comment]
Ok, @brocktopus, just added the other feature too. I couldn't resist. :-)
